
import os
import json
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_JUSTIFY, TA_CENTER, TA_LEFT

# Import Groq client from existing service or init new
import groq_service

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOWNLOAD_DIR = os.path.join(BASE_DIR, "downloads")

def generate_pdf_report(zone, analysis_data):
    """
    Generates a PDF report for the given zone and analysis data.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"Report_{zone}_{timestamp}.pdf"
    filepath = os.path.join(DOWNLOAD_DIR, filename)
    
    doc = SimpleDocTemplate(filepath, pagesize=A4,
                            rightMargin=72, leftMargin=72,
                            topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='Justify', alignment=TA_JUSTIFY))
    styles.add(ParagraphStyle(name='Center', alignment=TA_CENTER))
    styles.add(ParagraphStyle(name='SectionHeader', parent=styles['Heading2'], spaceBefore=12, spaceAfter=6, textColor=colors.teal))
    
    story = []
    
    # --- Title Page ---
    story.append(Spacer(1, 2*inch))
    story.append(Paragraph("INDUSTRIAL ENCHROACHMENT DETECTION REPORT", styles['Title']))
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph(f"Zone: {zone}", styles['Heading2']))
    story.append(Paragraph(f"Date: {datetime.now().strftime('%B %d, %Y')}", styles['Normal']))
    story.append(Spacer(1, 0.5*inch))
    # Add a logo or main image if available?
    # For now, just text.
    story.append(PageBreak())
    
    # --- Executive Summary (Generated by LLM) ---
    story.append(Paragraph("Executive Summary", styles['Heading1']))
    
    # Use existing executive summary from dashboard_insights if available
    exec_summary = analysis_data.get('dashboard_insights', {}).get('executive_summary', "No summary available.")
    story.append(Paragraph(exec_summary, styles['Justify']))
    story.append(Spacer(1, 12))
    
    # --- Compliance Status ---
    compliance_status = analysis_data.get('dashboard_insights', {}).get('compliance_status', 'Unknown')
    risk_level = analysis_data.get('dashboard_insights', {}).get('risk_level', 'Unknown')
    
    story.append(Paragraph(f"Compliance Status: <b>{compliance_status}</b>", styles['Normal']))
    story.append(Paragraph(f"Risk Level: <b>{risk_level}</b>", styles['Normal']))
    story.append(Spacer(1, 12))
    
    # --- Visual Analysis Findings ---
    story.append(Paragraph("Visual Analysis Findings", styles['Heading1']))
    
    groq_analysis = analysis_data.get('groq_analysis', {})
    if groq_analysis:
        story.append(Paragraph("AI-Based Observations:", styles['SectionHeader']))
        story.append(Paragraph(f"<b>Encroachment Status:</b> {groq_analysis.get('encroachment_status', 'N/A')}", styles['Normal']))
        story.append(Paragraph(f"<b>Construction Coverage:</b> {groq_analysis.get('construction_percentage', 'N/A')}%", styles['Normal']))
        story.append(Paragraph(f"<b>Vegetation Coverage:</b> {groq_analysis.get('vegetation_percentage', 'N/A')}%", styles['Normal']))
        story.append(Spacer(1, 6))
        story.append(Paragraph(f"<b>Detailed Observation:</b> {groq_analysis.get('explanation', 'N/A')}", styles['Justify']))
    
    story.append(Spacer(1, 12))
    
    # --- Images ---
    # We need to embed images. The paths in analysis_data are relative filenames in DOWNLOAD_DIR.
    images = analysis_data.get('images', {})
    
    image_list = [
        ("Satellite View (Current)", images.get('satellite_present')),
        ("Encroachment Analysis", images.get('encroachment_analysis')),
        ("Past Overlay", images.get('past_overlay')),
        ("Present Overlay", images.get('present_overlay'))
    ]
    
    story.append(Paragraph("Satellite Imagery Evidence", styles['Heading1']))
    
    for title, img_filename in image_list:
        if img_filename:
            img_path = os.path.join(DOWNLOAD_DIR, img_filename)
            if os.path.exists(img_path):
                story.append(Paragraph(title, styles['Heading3']))
                try:
                    # Resize image to fit page width (A4 width ~ 8.27 inch, margins 1 inch each -> ~6 inch usable)
                    im = Image(img_path, width=6*inch, height=3.5*inch, kind='proportional')
                    story.append(im)
                    story.append(Spacer(1, 12))
                except Exception as e:
                    print(f"Error adding image {img_filename} to PDF: {e}")
                    story.append(Paragraph(f"[Image: {title} - Not Available]", styles['Italic']))
            else:
                 story.append(Paragraph(f"[Image: {title} - File Not Found]", styles['Italic']))
        
    story.append(PageBreak())
    
    # --- Plot Compliance Data ---
    story.append(Paragraph("Plot Compliance Details", styles['Heading1']))
    
    plots = analysis_data.get('dashboard_insights', {}).get('plot_compliance', [])
    if plots:
        table_data = [['Plot ID', 'Industry', 'Built-Up Area', 'Risk Level', 'Status']]
        for plot in plots:
            table_data.append([
                plot.get('plotId', ''),
                plot.get('industryName', ''),
                str(plot.get('builtUpArea', '')),
                plot.get('riskLevel', ''),
                plot.get('verificationStatus', '')
            ])
            
        t = Table(table_data, colWidths=[1*inch, 2*inch, 1*inch, 1*inch, 1.5*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.teal),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ]))
        story.append(t)
    else:
        story.append(Paragraph("No specific plot compliance data available.", styles['Normal']))

    story.append(Spacer(1, 12))

    # --- Recommendations ---
    story.append(Paragraph("Recommended Actions", styles['Heading1']))
    recommendations = analysis_data.get('dashboard_insights', {}).get('recommendations', [])
    
    for rec in recommendations:
        story.append(Paragraph(f"• {rec}", styles['Normal']))
        story.append(Spacer(1, 6))

    # --- Footer ---
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph("Generated by Xcelerate 2026 AI Dashboard", styles['Italic']))
    
    # Build PDF
    try:
        doc.build(story)
        print(f"PDF Report generated: {filepath}")
        return {"status": "success", "filename": filename}
    except Exception as e:
        print(f"PDF Generation failed: {e}")
        return {"status": "error", "error": str(e)}

if __name__ == "__main__":
    # Test stub
    pass
